### ISSUE TITLE
update TCK so it can run on JDK 16

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/jsonp#284]
right now, there is a problem with weld:

```
[INFO] Running jakarta.jsonp.tck.api.jsonvaluetests.ClientTests
Apr 22, 2021 3:59:20 PM org.jboss.weld.bootstrap.WeldStartup startContainer
INFO: WELD-000101: Transactional services not available. Injection of @Inject UserTransaction not available. Transactional observers will be invoked synchronously.
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.058 s <<< FAILURE! - in jakarta.jsonp.tck.api.jsonvaluetests.ClientTests
[ERROR] jakarta.jsonp.tck.api.jsonvaluetests.ClientTests  Time elapsed: 0.047 s  <<< ERROR!
org.jboss.weld.exceptions.WeldException: WELD-001524: Unable to load proxy class for bean Implicit Bean [javax.enterprise.inject.Instance] with qualifiers [@Default] with class interface javax.enterprise.inject.Instance using classloader jdk.internal.loader.ClassLoaders$AppClassLoader@443b7951
	at org.jboss.weld.bean.proxy.ProxyFactory.getProxyClass(ProxyFactory.java:382)
	at org.jboss.weld.bean.builtin.AbstractFacadeBean.initializeAfterBeanDiscovery(AbstractFacadeBean.java:61)
...
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.jboss.classfilewriter.ClassFile
	at org.jboss.weld.bean.proxy.ProxyFactory.newClassFile(ProxyFactory.java:503)
	at org.jboss.weld.bean.proxy.ProxyFactory.createProxyClass(ProxyFactory.java:458)
	at org.jboss.weld.bean.proxy.ProxyFactory.getProxyClass(ProxyFactory.java:374)
	... 9 more
```

**Comment by jansupol** [comment]
You need to use weld 3.1.7.Final+ for JDK 16.

**Comment by jansupol** [comment]
Ehm....a Jakarta EE 9 equivalent :)

**Comment by lukasj** [comment]
I know. I just don't want to do it right away hoping someone else can provide PR for it ;-)

**Comment by jbescos** [comment]
TCK should be working after this PR https://github.com/eclipse-ee4j/jsonp/pull/295

**Comment by lukasj** [comment]
yes
