### ISSUE TITLE
[Clarification] Should generator.write("key").write("value") be allowed in objects?

### ISSUE THREAD

**Issue by aguibert** [eclipse-ee4j/jsonp#78]
I only know of 2 JSON-P 1.1. implementations (Glassfish RI and Johnzon Core), and these two impls seem to interpret this differently, so I'm wondering which interpretation is correct.

The RI seems to allow writing keys/values separately, but Johnzon Core throws the following exception:
```
javax.json.stream.JsonGenerationException: write(param) is only valid in arrays
	at org.apache.johnzon.core.JsonGeneratorImpl.checkArray(JsonGeneratorImpl.java:614)
	at org.apache.johnzon.core.JsonGeneratorImpl.write(JsonGeneratorImpl.java:378)
	at org.eclipse.yasson.internal.serializer.StringTypeSerializer.serialize(StringTypeSerializer.java:59)
	at org.eclipse.yasson.internal.serializer.StringTypeSerializer.serialize(StringTypeSerializer.java:1)
	at org.eclipse.yasson.internal.serializer.AbstractValueTypeSerializer.serialize(AbstractValueTypeSerializer.java:51)
	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serializerCaptor(AbstractContainerSerializer.java:96)
	at org.eclipse.yasson.internal.serializer.ObjectSerializer.marshallProperty(ObjectSerializer.java:94)
	at org.eclipse.yasson.internal.serializer.ObjectSerializer.serializeInternal(ObjectSerializer.java:63)
	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:64)
	at org.eclipse.yasson.internal.Marshaller.serializeRoot(Marshaller.java:119)
	at org.eclipse.yasson.internal.Marshaller.marshall(Marshaller.java:75)
	at org.eclipse.yasson.internal.JsonBinding.toJson(JsonBinding.java:98)
	at org.eclipse.yasson.SimpleTest.testSimpleSerialize(SimpleTest.java:48)
        <rest of the stack is junit runner>
```

This is the specific method I ran into:
https://static.javadoc.io/javax.json/javax.json-api/1.1.2/javax/json/stream/JsonGenerator.html#write-java.lang.String-
but the same would apply for all of the `write(param)` methods.

This issue has been carried over from https://github.com/eclipse/yasson/issues/96

**Comment by m0mus** [comment]
I would say that we should not restrict it. There are some use cases (and we faced them when we were working on Yasson) where it's needed to use write(param) in objects. The spec says that JsonGenerationException must be thrown in case write(param) is not called within an array or root context. It should've been removed from the spec, but wasn't because we missed it.

**Comment by aguibert** [comment]
thanks for clarification @m0mus, that answers my question
