### ISSUE TITLE
JSON-P API bundle does not find Glassfish RI in an OSGi environment

### ISSUE THREAD

**Issue by JochenHiller** [eclipse-ee4j/jsonp#96]
I am trying to use JSON-P API and Glassfish JSON-P RI within an OSGi framework (both Apache Felix and Eclipse Concierge) for testing within Eclipse SmartHome framework. See also https://github.com/eclipse/smarthome/issues/4741

It does work when using org.glassfish:javax.json:1.1. This JAR file includes both
* the API packages (javax.json.*)
* the implementation (org.glassfish.json.*)

When moving to version 1.1.2 the Glassfish bundle has now been split to
* an API bundle (I am using javax.json:javax.json-api:1.1, I think the version before JakartaEE)
* Glassfish RI (org.glassfish:javax.json:1.1.2) 

Now it does not work anymore: See console (same for Apache Felix)

```
---------------------------------------------------------
  Concierge OSGi 5.1.0.SNAPSHOT-20171014090828 on Mac OS X 10.13.5 starting ... (default) startlevel=3
---------------------------------------------------------
---------------------------------------------------------
  Framework started in 0.005 seconds.
---------------------------------------------------------
____________________________
Welcome to Apache Felix Gogo

g! ! Failed to start bundle org.eclipse.concierge.samples.jsonb-0.0.0, exception activator error Provider org.glassfish.json.JsonProviderImpl not found from: javax.json.spi.JsonProvider:provider#99
org.osgi.framework.BundleException: Error starting bundle [org.eclipse.concierge.samples.jsonb-0.0.0]
	at org.eclipse.concierge.BundleImpl.activate0(BundleImpl.java:600)
	at org.eclipse.concierge.BundleImpl.activate(BundleImpl.java:552)
	at org.eclipse.concierge.BundleImpl.start(BundleImpl.java:506)
	at aQute.launcher.Launcher.startBundles(Launcher.java:517)
	at aQute.launcher.Launcher.activate(Launcher.java:423)
	at aQute.launcher.Launcher.run(Launcher.java:301)
	at aQute.launcher.Launcher.main(Launcher.java:147)
Caused by: javax.json.JsonException: Provider org.glassfish.json.JsonProviderImpl not found
	at javax.json.spi.JsonProvider.provider(JsonProvider.java:99)
	at java.util.Optional.orElseGet(Optional.java:267)
	at org.eclipse.yasson.internal.JsonBinding.<init>(JsonBinding.java:41)
	at org.eclipse.yasson.internal.JsonBindingBuilder.build(JsonBindingBuilder.java:63)
	at javax.json.bind.JsonbBuilder.create(JsonbBuilder.java:108)
	at org.concierge.sample.jsonb.JsonbHelper.toJson(JsonbHelper.java:14)
	at org.concierge.sample.jsonb.Activator.start(Activator.java:27)
	at org.eclipse.concierge.BundleImpl.activate0(BundleImpl.java:575)
	... 6 more
Caused by: java.lang.ClassNotFoundException: org.glassfish.json.JsonProviderImpl
	at org.eclipse.concierge.BundleImpl$Revision$BundleClassLoader.findClass(BundleImpl.java:2503)
	at org.eclipse.concierge.BundleImpl$Revision$BundleClassLoader.loadClass(BundleImpl.java:2482)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at javax.json.spi.JsonProvider.provider(JsonProvider.java:96)
	... 13 more
```

If I check the code at https://github.com/javaee/jsonp/blob/master/api/src/main/java/javax/json/spi/JsonProvider.java#L99 (which I assume is the code for javax.json:javax.json-api:1.1 bundle, pre JakartaEE) I see

```
        try {
            Class<?> clazz = Class.forName(DEFAULT_PROVIDER);
            return (JsonProvider) clazz.newInstance();
        } catch (ClassNotFoundException x) {
            throw new JsonException(
                    "Provider " + DEFAULT_PROVIDER + " not found", x);
        } catch (Exception x) {
```

I think this is bad on at least these concepts:
* Class.forName is discouraged in a dynamic environment like OSGi (e.g. read http://blog.hargrave.io/2007/09/classforname-caches-defined-class-in.html, https://blog.osgi.org/2011/05/what-you-should-know-about-class.html)
* in general the ServiceLoader concepts does not really match well with OSGi, read https://blog.osgi.org/2013/02/javautilserviceloader-in-osgi.html

I think you should carefully check the OSGi R5 Enterprise Spec, Chapter 133: ServiceLoader Mediator Specification to understand if and how the JSON-P and Glassfish RI can be implemented in an OSGi friendly way.

**Comment by vorburger** [comment]
We ran into this as well (in OpenDaylight; see https://jira.opendaylight.org/browse/NEUTRON-197 and https://jira.opendaylight.org/browse/NEUTRON-200), because -like you describe- EclipseLink Moxy (org.eclipse.persistence.moxy) in their in 2.7.1 to 2.7.3 upgrade changed from org.glassfish:javax.json 1.0.4 to javax.json:javax.json-api 1.1.2 - and broke applications running on OSGi, as just also reported on https://bugs.eclipse.org/bugs/show_bug.cgi?id=539939.

As a work around, in ODL where we can't wait we for now fell back to forcing (painfully, urgh; Karaf features are a PITA) usage of org.glassfish:javax.json 1.0.4 instead of using javax.json:javax.json-api + org.glassfish:javax.json 1.1.2 for EclipseLink Moxy 2.7.3, but this is of course suboptimal; we'd love to consume the latest and greatest from this project!

I'm not sure what the best solution to this really is... @kaikreuzer shout if have any smart ideas!

**Comment by lukasj** [comment]
can you try 1.1.3?

**Comment by Cousjava** [comment]
This occurs for me for 1.1.3 in Payara

**Comment by lukasj** [comment]
even after applying this change: https://github.com/javaee/glassfish/commit/24cd6 ?

**Comment by Cousjava** [comment]
See my edit, Payara uses jsonp to run asamin commands and is part of the nucleus, see payara/payara@f5581c4 . Glassfish merely provides Jsonp , it doesn't make use of it.

**Comment by lukasj** [comment]
Should be fixed with javax.json:1.1.4 and jakarta.json:1.1.5
